services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: receiptdb
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: